name: angular-build
on:
    pull_request:
        paths:
            - backend/**
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: 16.x
            - run: cd ./backend/
            - run: npm ci
            - run: npm run build

